export const products = [
  {
    _id: 1,
    title: "Butterfly Sword",
    category: ["weapon", "sword"],
    desc: "A sword used by the Seven Heroes' Wagnas in countless battles. It is said that the blade lends heroic strength to the wielder.",
    img: "https://img.game8.co/4041614/070396504265f9687f848b59cc7dd063.png/show",
    price: 200,
  },
  {
    _id: 2,
    title: "Dragon Blade",
    category: ["weapon", "sword"],
    desc: "A sword crafted from dragon scales by an ancient civilization. It is sharp enough to even pierce thick dragon hide.",
    img: "https://img.game8.co/4041621/c6d27a4571a29b91097a17b5751fc56e.png/show",
    price: 100,
  },
  {
    _id: 3,
    title: "Obsidian Sword",
    category: ["weapon", "sword"],
    desc: "A hard and heavy sword made from pitch black obsidian.",
    img: "https://img.game8.co/4041619/f7d68e519506c4230337bb09d4e178f8.png/show",
    price: 50,
  },
  {
    _id: 4,
    title: "Crimson Dragon",
    category: ["weapon", "greatsword"],
    desc: "A greatsword used by the Seven Heroes' Noel in countless battles. It is said to contain the memories of those battles within its blade.",
    img: "https://img.game8.co/4041574/ef9b5b428b196b857ecaf2e5005c55a7.png/show",
    price: 200,
  },
  {
    _id: 5,
    title: "Hauteclaire",
    category: ["weapon", "greatsword"],
    desc: "???",
    img: "https://img.game8.co/4041580/78b57ee0e66a150d2a3315fdc5ec7ae0.png/show",
    price: 100,
  },
  {
    _id: 6,
    title: "Cross Claymore",
    category: ["weapon", "greatsword"],
    desc: "An imporved version of the standard claymore, it is capable of even more powerful blows.",
    img: "https://img.game8.co/4041573/7ff156a186b06c91f97de6754e17982d.png/show",
    price: 50,
  },
  {
    _id: 7,
    title: "Nautilus Spear",
    category: ["weapon", "spear"],
    desc: "A spear used by the Seven Heroes' Subier in countless battles. The memories contained within the weapon are said to lend their strength to the wielder.",
    img: "https://img.game8.co/4041356/8ade0f4b8af9e345ee14a7d8ba026a18.png/show",
    price: 200,
  },
  {
    _id: 8,
    title: "Divine Longinus",
    category: ["weapon", "spear"],
    desc: "A spear imbued with sacred energy; it has existed since ancient times. It is capable of linking thoughts together to perform a powerful attack.",
    img: "https://img.game8.co/4041364/d679ddff08fe1300b7efed6831b7eda8.png/show",
    price: 100,
  },
  {
    _id: 9,
    title: "Obsidian Lance",
    category: ["weapon", "spear"],
    desc: "A spear made with an obsidian tip. The finely polished tip is both hard and sharp.",
    img: "https://img.game8.co/4041361/a333ae97dae101e42c50695fd649d6a8.png/show",
    price: 50,
  },
  {
    _id: 10,
    title: "Dragonscale Axe",
    category: ["weapon", "axe"],
    desc: "A axe used by the Seven Heroes' Noel in countless battles. It is said to lend the wielder the heroic strength imbued within its blade.",
    img: "https://img.game8.co/4041529/a6524c922cbfedc7c8790825598a57d8.png/show",
    price: 200,
  },
  {
    _id: 11,
    title: "Great Axe",
    category: ["weapon", "axe"],
    desc: "A high quality axe that is exhilarating to use. It is so sharp that it cuts through just about anything with ease.",
    img: "https://img.game8.co/4041533/0e565343332665a827432b927dbbcc90.png/show",
    price: 100,
  },
  {
    _id: 12,
    title: "Amethyst Axe",
    category: ["weapon", "axe"],
    desc: "A battle axe made with magical amethyst stones. If used long enough, it can create a phandom double of the wielder.",
    img: "https://img.game8.co/4041528/7c6d154608886bdd4500c6d051f6eb9b.png/show",
    price: 50,
  },
  {
    _id: 13,
    title: "Marionette's Club",
    category: ["weapon", "club"],
    desc: "A club used by the Seven Heroes' Bokhohn in countless battles. It is said to lend the wielder the heroic strength imbued within its shaft.",
    img: "https://img.game8.co/4041421/30da4dfa3aac67c0837db6fd13a4f846.png/show",
    price: 200,
  },
  {
    _id: 14,
    title: "Holy Buster",
    category: ["weapon", "club"],
    desc: "A club imbued with holy energy that is detested by evil. It unleashes a powerful light that can obliterate any malignant beings before it.",
    img: "https://img.game8.co/4041419/083aa76240c1896c234b2fe59b549c69.png/show",
    price: 100,
  },
  {
    _id: 15,
    title: "Amber Mace",
    category: ["weapon", "club"],
    desc: "A club designed solely for causing destruction. It feaatures the highest attack power of any club.",
    img: "https://img.game8.co/4041418/aa6680bc2a546cb2aaa72945ff6ec75f.png/show",
    price: 50,
  },
  {
    _id: 16,
    title: "Temptation Blade",
    category: ["weapon", "rapier"],
    desc: "A shortword used by the Seven Heroes' Rocbouquet in countless battles. Its blade is said to contain the magic that left countless men helpless while in her presence.",
    img: "https://img.game8.co/4041217/bf5ceed7441274ac7c22aef0138e7efd.png/show",
    price: 200,
  },
  {
    _id: 17,
    title: "Star of Ilorina",
    category: ["weapon", "rapier"],
    desc: "A beautiful shortsword tht captivates all who see it. The enemies cut down before it look like scattering flowers.",
    img: "https://img.game8.co/4041218/45e2a034c038c328c8196a30ecb35ecf.png/show",
    price: 100,
  },
  {
    _id: 18,
    title: "Terra Blade",
    category: ["weapon", "rapier"],
    desc: "A shortsword imbued with earth and holy energies. It grants the power of the earth to the wielder and their allies.",
    img: "",
    price: 50,
  },
  {
    _id: 19,
    title: "Soulreaper Bow",
    category: ["weapon", "bow"],
    desc: "A bow used by the Seven Heroes' Kzinssie in countless battles. Its arrows steal the life force of those they pierce.",
    img: "https://img.game8.co/4041183/38306a0e3610da2f1a6d4cada8bc359d.png/show",
    price: 200,
  },
  {
    _id: 20,
    title: "Starlight Bow",
    category: ["weapon", "bow"],
    desc: "A bow created in the image of a star. Arrows fired from it are said to be capable of reaching the heavenly bodies in the night sky.",
    img: "https://img.game8.co/4041176/5d943625ab463c4a3aef7dcb039dbc2f.png/show",
    price: 100,
  },
  {
    _id: 21,
    title: "Eris's Bow",
    category: ["weapon", "bow"],
    desc: "A mysterious bow that is capable of maximizing the wielder's attack strength. It displays unparalleled power when used by a master archer.",
    img: "https://img.game8.co/4041175/4ac2fe11363edee6062554671cd7c0fb.png/show",
    price: 50,
  },
];
